### ISSUE TITLE
Joel to create front-end HTML structure

### ISSUE THREAD

**Issue by mjtic** [RyanDamron/US-OpenCourts#10]

**Comment by RyanDamron** [comment]
Will need 4 HTML files:
-Sign-in page
-Search page
-Results page
-Find One page

Refer to wireframe for reference
No need to style these, just create basic skeleton.

[https://docs.google.com/presentation/d/1iqgPYTN18WJE1DUcX5ImmPhfMSJX9ewP8Aotjrgt7Yw/edit?usp=sharing](url)
