### ISSUE TITLE
Joel to create "/" HTML front-end entails signup, signin form

### ISSUE THREAD

**Issue by mjtic** [RyanDamron/US-OpenCourts#14]

**Comment by RyanDamron** [comment]
Create HTML sign-in page

Refer to wireframe for reference
No need to style these, just create basic skeleton.

[https://docs.google.com/presentation/d/1iqgPYTN18WJE1DUcX5ImmPhfMSJX9ewP8Aotjrgt7Yw/edit?usp=sharing](https://github.com/RyanDamron/US-OpenCourts/issues/url)
